### ISSUE TITLE
VertSpit Colors

### ISSUE THREAD

**Issue by AlessandroYorba** [AlessandroYorba/Sidonia#4]
Both Sidonia and Monrovia have a minimal VertSplit. While I like the look of having no background in the VertSplit, and just having the dark pipe chars, do you think it should change to something more traditional? 
![screen shot 2017-02-20 at 4 48 47 pm](https://cloud.githubusercontent.com/assets/11221489/23146549/a5860314-f78c-11e6-8a42-07b996203c22.png)

Here a version with a light background and a dark foreground:
![screen shot 2017-02-20 at 4 49 32 pm](https://cloud.githubusercontent.com/assets/11221489/23146573/d5fd8666-f78c-11e6-8852-51fdbd5ef26e.png)

Here's a version with a light background with light foreground:
![screen shot 2017-02-20 at 4 49 58 pm](https://cloud.githubusercontent.com/assets/11221489/23146583/fb47ca58-f78c-11e6-942d-57f51b593e78.png)

**Comment by tiberiuichim** [comment]
I usually run my vim with 

     set fillchars=vert:│,fold:━     " this changes characters used for splits and horizontal folding

Notice the unicode characters. This makes the pipes behave like a real line, so I prefer (as a general rule, I'm despacio and alduin) no background on the pipes.

**Comment by AlessandroYorba** [comment]
@tiberiuichim thanks. In that case, I'll leave it as is, seeing how users might have their own override settings in their vimrc.
